### ISSUE TITLE
Retain cycle at TraitQueryLayoutSet

### ISSUE THREAD

**Issue by someyura** [DeclarativeHub/Layoutless#16]
I've noticed then whenever I'm using `TraitQueryLayoutSet` by calling `layoutSet(...)`, my subviews stay in memory even when the view controller itself is closed and destroyed. In my case, it was an instances of `MKMapView` which are quite heavy so it was easy to spot.

<img width="297" alt="Screenshot 2020-11-29 at 23 15 54" src="https://user-images.githubusercontent.com/24977629/100554238-6f675380-32a4-11eb-93d6-677a8f58eca2.png">

I've tried to fix it and memory leaks are gone. But since I don't want to break anything, I've spent some time figuring out how Layoutless works and what might cause the problem. So here is what I've got:

1. `TraitQueryLayoutSet` has a property called `parentRevertable` that is used to store other `Revertables`. So far it looks to me that `Revertable` is used for deactivating constraints and removing subviews from the hierarchy. Sort of "reverting" applied changes. 
2. `Revertable` which is created when we call `TraitQueryLayoutSet.layout(in container: UIView)` has an _implicit strong capture_ of `self` what creates a retain cycle that looks like `TraitQueryLayoutSet` → `Revertable` → `Closure` → `TraitQueryLayoutSet`. Unfortunately, I wasn't able to capture it using XCode memory graph so I don't have a proof that that's exactly how it works. 
3. To break this cycle, I've replaced this capture with a _weak_ one. The obvious side-effect of this is that when the closure will be performed, the `self` might be `nil` and some changes won't be applied.
4. But if I'm right, this is totally fine because we call `TraitQueryLayoutSet.layout(in container: UIView)`, layout set adds itself into the passed `container` using `___associatedObjects` using a strong link, because the used policy is `OBJC_ASSOCIATION_RETAIN_NONATOMIC`. So while our `container` is alive, `TraitQueryLayoutSet` will be alive too since we have a strong link. And when your `container` is destroyed, there is no need to keep `TraitQueryLayoutSet` since it's responsible only for layout updates.

So if I'm got this right, my pull request should fix the problem just fine. Otherwise, please, correct me on any of the above.

**Comment by srdanrasic** [comment]
Thank for the explanation and the fix. I've now merged your PR.
