### ISSUE TITLE
Manual autolayout block and hierarchies

### ISSUE THREAD

**Issue by pankkor** [DeclarativeHub/Layoutless#4]
Hey, nice work! The only thing I found a bit hard is lacking of documentation and examples.

I have 3 questions:
1. A question regarding using autolayout manually with Layoutless.
For instance I have a stack layout which and I want to show a `view` on a bottom right, or do some more sophisticated stuff.

```
return group(
    stack(.vertical)(
        firstLabel,
        secondLabel
        ).sizing(toWidth: 280).centeringInParent(relativeToSafeArea: true).layoutRelativeToDescendent(view) { ... }
}
```
I've tried a bunch of ways to do  it and I usually get an exception that views are in different hierarchies.

2. And what if I want to manage `view` both with layoutless and with manual autolayout block?
Like
```
return group(
    stack(.vertical)(
        firstLabel,
        secondLabel
        ).sizing(toWidth: 280).centeringInParent(relativeToSafeArea: true),
    view.centeringHorizontallyInParent.layoutRelativeToDescendent(/* what should I put here? */)
}
```

3. How do you manage adding views to another views using Layoutless?
So if I have
```
    public var imageView = ImageView(myImage)
```
Can I add a `view` to `imageView` and manage it's layout with Layoutless without subclassing ImageView?

**Comment by srdanrasic** [comment]
Hi @pankkor ,

3.

You can do something like:

```swift
var subviewsLayout: AnyLayout {
    return view.fillingParent().embedding(in: imageView).fillingParent()
}
```

You can also do (when doing outside of subviewsLayout):

```swift
view.fillingParent().layout(in: imageView)
```

2.

```swift
override func defineLayout() {
    super.defineLayout()
    // Do manual layout below:
    view.widthAnchor.constrain...
}
```

1.

This should be the same case as in 1. You might need to embed whole group in a dummy view though: `return group(...).embedding(in: View()).fillingParent()`

**Comment by pankkor** [comment]
@srdanrasic thanks,
1. So I try to do something like:
```
    var firstLabel = UILabel()
    var secondLabel = UILabel()
    var manualView = UIView()

    public override var subviewsLayout: AnyLayout {
        return group(
            stack(.vertical, spacing: 20, alignment: .center)(
                firstLabel,
                secondLabel
            )
            .sizing(toWidth: 280)
            .centeringInParent(relativeToSafeArea: true)
            .layoutRelativeToDescendent(manualView, layout: { (view, stackView) in
                stackView.bottomAnchor.constraint(equalTo: view.topAnchor).isActive = true
                stackView.trailingAnchor.constraint(equalTo: view.leadingAnchor).isActive = true
            }),
            manualView.sizing(toWidth: 20.0, height: 20.0)
        ).embedding(in: View()).fillingParent()
    }
```
and still get exception that views are in different hierarchies. I even tried to manually added `manualView` as a subview of self.view but without luck. What do I do wrong?

What's the use case of ```layoutRelativeToDescendent```? I didn't find any examples. Would really appreciate one.

**Comment by srdanrasic** [comment]
I hope this was eventually resolved so I'll close the issue.
