### ISSUE TITLE
Latest release not available on Cocoapods

### ISSUE THREAD

**Issue by glenwong** [DeclarativeHub/Layoutless#5]
Not sure if you are aware but I noticed that the latest version available on Cocoapods is 0.1.3.

**Comment by genkernel** [comment]
+1. Layoutless looks promising!
I noticed there were just 2 new commits since 0.1.3. Not sure how important code change is but going to try with 0.1.3 version from CocoaPods anyways.

**Comment by srdanrasic** [comment]
Thanks, this is fixed now.
